# Generated by Django 4.0.5 on 2022-06-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notefy_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='last_modified_on',
            field=models.DateField(auto_now=True),
        ),
    ]
