# Generated by Django 4.0.5 on 2022-06-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notefy_site', '0002_note_last_modified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
